### ISSUE TITLE
ros plugins don't  appear in qt.

### ISSUE THREAD

**Issue by wangzhaodong123** [ros-industrial/ros_qtc_plugin#129]
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
== Output redirected to setup.log
== 
== ROS Qt Plugin Git()
== Checking build dependencies
==  Installed      : build-essential
==  Installed      : libgl1-mesa-dev
==  Installed      : libqtermwidget57-0-dev
==  Installed      : python-catkin-tools
==  Installed      : libyaml-cpp-dev
== Entering /home/wangzhaodong/qt-creator source path
== Updating Qt Creator from github.com
==  Fetching into qt-creator
==  0:0:3 elapsed
==  Pulling into qt-creator
==  0:0:5 elapsed
== Entering /home/wangzhaodong/qt-creator-build build path
==  Cleaning project QtCreator
==
==  0:0:7 elapsed

**Comment by Levi-Armstrong** [comment]
Sorry, don't fully understand what you were trying do. Can you walk me through the steps that generated the error?

**Comment by oxoocoffee** [comment]
I think it would be great to attach setup.log here?

**Comment by Levi-Armstrong** [comment]
@wangzhaodong123 Are you doing rviz plug-in development? If so, I know there is an issue if you build it using the IDE, because the environment is pointing to Qt 5.7 when the plug-in needs to be built with another version. I have started to work on this but have not had time to finish, but the way to solve this and still use the IDE is build it from the terminal passing the codeblock generator flag and then right click on the project name in the IDE and select reload code model after it has been built. Once you have passed the codeblock generator flag once you dont have to pass it again for other builds as long as you have not performed a clean. Also you will not have to refresh the code model each time unless new files were added.
