### ISSUE TITLE
good install method, I recommend！

### ISSUE THREAD

**Issue by wojiaojiao** [ros-industrial/ros_qtc_plugin#139]
The following methods are installed  qt creator and plugin-ros at the same time,Very convenient and avoid the error their versions do not match.
// for Ubuntu 14.04

sudo add-apt-repository ppa:levi-armstrong/qt-libraries-trusty
sudo add-apt-repository ppa:levi-armstrong/ppa  
sudo apt-get update && sudo apt-get install qt57creator
sudo apt-get update && sudo apt-get install qt57creator-plugin-ros

**Comment by MaxWattage** [comment]
Hi,
I have the current version of Qt Creator, which reports itself as being "Qt Creator 4.3.1", "Based on Qt 5.9.1 (GCC 5.3.1 20160406 (Red Hat 5.3.1-6), 64 bit)".
I use this for many software projects, but I would now like to use ROS as well.

The installation instructions at https://github.com/ros-industrial/ros_qtc_plugin/wiki/1.-How-to-Install-(Users)  ,for users of Ubuntu 16.04 LTS, do not seem to work (for me).

I don't get any errors during install, but if I test the installation by opening Qt Creator and to going to import a project, then ROS isn't listed as an available as a project type. i.e. ROS isn't installed in this Qt Creator.

How can I make ROS work with my Qt Creator installation?
Thank you

**Comment by wojiaojiao** [comment]
@MaxWattage 
Because your Qt Creator cersion is 4.3.1!qt57creator-plugin-ros need qt creator version is 5.7.1
please try:
sudo add-apt-repository ppa:levi-armstrong/qt-libraries-xenial  
sudo add-apt-repository ppa:levi-armstrong/ppa  
sudo apt-get update && sudo apt-get install qt57creator
sudo apt-get update && sudo apt-get install qt57creator-plugin-ros

**Comment by MaxWattage** [comment]
Well, that now gives me two versions of Qt on my machine.
My original "Qt 5.9.1 Creator" version, and the "Qt 5.7.1 Creator" version.

The Qt 5.7.1 version correctly shows the "Import ROS Workspace" option, whereas my original installation still doesn't.

However, when I load my existing code project(s) into the 5.7.1 version it is broken and won't compile.
I get the following compiler message:
    Project ERROR: Unknown module(s) in QT: serialbus
    18:35:06: The process "/usr/lib/x86_64-linux-gnu/qt5/bin/qmake" exited with code 3.
    Error while building/deploying project ModbusMasterTest (kit: Desktop)

I have spent several hours Googling this compile problem without finding a solution that works.
This same project still compiles perfectly in my original Qt 5.9.1 installation.

NB: I'm not very happy that installing ROS requires me to use this obsolete Qt 5.7.1 version, which won't even let me compile my existing projects. Why doesn't ROS support being installed into the current version of Qt 5.9.1?

**Comment by Levi-Armstrong** [comment]
>NB: I'm not very happy that installing ROS requires me to use this obsolete Qt 5.7.1 version, which won't even let me compile my existing projects. Why doesn't ROS support being installed into the current version of Qt 5.9.1?

Given that Qt was not regularly keeping the binary release updated with the latest version in Indigo, it was decided to manage our own Qt Libraries since the plugins will only work with the exact version from which it was built for.  It currently is not the latest on kinetic but it soon will change where the ROS version is greater than what you can get through apt-get. So you must use Qt 5.7.1 if you want to use the ROS Plug-in, gut that does not stop you from building Qt 5.9.1  application, just update your kit in Qt Creator to use the particular version of Qt you want to build with.

**Comment by Levi-Armstrong** [comment]
>However, when I load my existing code project(s) into the 5.7.1 version it is broken and won't compile.
I get the following compiler message:
Project ERROR: Unknown module(s) in QT: serialbus
18:35:06: The process "/usr/lib/x86_64-linux-gnu/qt5/bin/qmake" exited with code 3.
Error while building/deploying project ModbusMasterTest (kit: Desktop)

Does this error occur when building a ROS workspace?

**Comment by MaxWattage** [comment]
I don't have any code yet that uses a ROS workspace, I've only just installed ROS, and haven't yet learned how to use it.
What I do have a project that uses serial ports, and the modbus components from the Qt "serialport" and Qt "serialbus" components respectively.

My aim is to develop a ROS project that will use the "serialport" and "serialbus" components to communicate with the robot.
However, if it turns out that ROS only works with Qt 5.7.1, and the "serialbus" widget only works with Qt 5.9.1 than that is a big problem for the project.

**Comment by Levi-Armstrong** [comment]
>However, if it turns out that ROS only works with Qt 5.7.1, and the "serialbus" widget only works with Qt 5.9.1 than that is a big problem for the project.

ROS should work with any version of Qt, it is the ROS Qt Creator Plugin which requires Qt 5.7.1. When developing using Qt Creator (Qt 5.7.1) you must configure your kit within Qt Creator to use Qt 5.9.1 when building Qt Projects. Just because Qt Creator was built using Qt 5.7.1 does not prevent you from building other application using different version of Qt.

**Comment by wojiaojiao** [comment]
@Levi-Armstrong 
you must configure your kit within Qt Creator to use Qt 5.9.1 when building Qt Projects

**Comment by MaxWattage** [comment]
Well, I've spent a good 8 hours trying to configure a kit within Qt Creator to use Qt 5.9.1, without any joy.

I did find that I could stop it using Qt4 by using "export QT_SELECT=5"
However, the version of Qt5 with Ubuntu 16.04 LTS seems to be fixed at 5.5.1, which does not include the QtSerialbus libraries I need. (apparently QtSerialbus was first introduced in Qt 5.6.0)

That's why I need Qt 5.9.1, which also happens to be the version installed by the latest Qt Creator 5.9.1.
However, the Qt 5.9.1 gets installed by the maintenance tool in my local directory "/home/nicholaslee/Qt/5.9.1/gcc_64/bin", rather than simply updating the system's Qt5 installation.

I tried many combination, but my code to build in "Qt Creator 5.7.1" but project builds still fail when it  tries to use a kit configured to use Qt 5.9.1, 

Here is the compilation window output,..

02:43:59: Running steps for project ModbusMasterTest...
02:43:59: Configuration unchanged, skipping qmake step.
02:43:59: Starting: "/usr/bin/make" 
/home/nicholaslee/Qt/5.9.1/gcc_64/bin/qmake -o Makefile ../ModbusMasterTest/ModbusMasterTest.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/home/nicholaslee/Qt/5.9.1/gcc_64/bin/uic: relocation error: /home/nicholaslee/Qt/5.9.1/gcc_64/bin/uic: symbol _ZdlPvm, version Qt_5 not defined in file libQt5Core.so.5 with link time reference
/home/nicholaslee/Qt/5.9.1/gcc_64/bin/uic: relocation error: /home/nicholaslee/Qt/5.9.1/gcc_64/bin/uic: symbol _ZdlPvm, version Qt_5 not defined in file libQt5Core.so.5 with link time reference
/home/nicholaslee/Qt/5.9.1/gcc_64/bin/uic: relocation error: /home/nicholaslee/Qt/5.9.1/gcc_64/bin/uic: symbol _ZdlPvm, version Qt_5 not defined in file libQt5Core.so.5 with link time reference
/home/nicholaslee/Qt/5.9.1/gcc_64/bin/uic ../ModbusMasterTest/optionsdlg.ui -o ui_optionsdlg.h
/home/nicholaslee/Qt/5.9.1/gcc_64/bin/uic: relocation error: /home/nicholaslee/Qt/5.9.1/gcc_64/bin/uic: symbol _ZdlPvm, version Qt_5 not defined in file libQt5Core.so.5 with link time reference
Makefile:1105: recipe for target 'ui_optionsdlg.h' failed
make: *** [ui_optionsdlg.h] Error 127
02:44:00: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project ModbusMasterTest (kit: Desktop)
The kit Desktop has configuration issues which might be the root cause for this problem.
When executing step "Make"
02:44:00: Elapsed time: 00:01.

**Comment by Levi-Armstrong** [comment]
Are you able to provide a sample project which recreates the issue and I will see if I can get it to build with a local install of Qt 5.9.1?

**Comment by Levi-Armstrong** [comment]
I believe it is something to do with the environment variables in project>build>System Environment.

I would remove any reference to qt57 from the following environment variables:
LD_LIBRARY_PATH
PATH
PKG_CONFIG_PATH

Then update this environment variable to point to the local install directory of qt:
QTDIR

**Comment by MaxWattage** [comment]
Ok, it seems to be working now. (for a given value of working)

I updated the three environment variables and now mt oroject compiles.

The caveats to this are that the 'Kit' Desktop (default) has a yellow warning '!' next to it and the pop-up message I get when I hover over this says that...
Warning: CMake version is unsupported. Please update to version 3.0 or later
Warning: CMake tool does not support configured generator.
Warning: CMake tool does not generate a CodeBlocks file. Qt will not be able to parse the CMake project

These warnings are gibberish to me.

Oh, and I could only get Qt Creator 5.7.1. to start if I added the following suffix to the icon's command parameter:
 -noload Welcome -noload QmlDesigner -noload QmlProfiler

Without this, Qt Creator 5.7.1 fails to open, giving an OpenGL error.
(The latest Qt Creator 4.3.1 needs no such modification to start it)

Also, on start-up I now get a pop-up window saying...
The following plugins have errors and cannot be loaded:
QbsProjectManager
Details:
/opt/qt57/lib/x86_64-linux-gnu/qtcreator/plugins/libQbsProjectManager.so: Cannot load library /opt/qt57/lib/x86_64-linux-gnu/qtcreator/plugins/libQbsProjectManager.so: (libqbscore.so.1.7: cannot open shared object file: No such file or directory)

**Comment by Levi-Armstrong** [comment]
>Also, on start-up I now get a pop-up window saying...
The following plugins have errors and cannot be loaded:
QbsProjectManager
Details:
/opt/qt57/lib/x86_64-linux-gnu/qtcreator/plugins/libQbsProjectManager.so: Cannot load library /opt/qt57/lib/x86_64-linux-gnu/qtcreator/plugins/libQbsProjectManager.so: (libqbscore.so.1.7: cannot open shared object file: No such file or directory)

I have been trying to get everything released for armhf and in the process I upgraded the qbs library which has now broken things in qtcreator. I will be working today to upgrade Qt Creator to 4.3.0, sorry for the inconvenience.

**Comment by Levi-Armstrong** [comment]
Note: Everything should work except feature from the QbsPlugin which if you are developing with ros you should be OK.

**Comment by MaxWattage** [comment]
Hi, I have received your software update through the PPA, but I can detect no changes to the functionality.

All the bugs/issues I reported above still seem to be present. I even re-booted and tested again, just to be sure.

What changes in the behaviour should I have seen?

**Comment by Levi-Armstrong** [comment]
There are currently no changrd just the upgrade to the qbs library. I have a PR in review for upgrading to Qt Creator 4.3.

**Comment by Levi-Armstrong** [comment]
Everything has been upgraded to 4.3.1.

**Comment by Levi-Armstrong** [comment]
@wojiaojiao The install procedure has been updated per your recommendation.

**Comment by Levi-Armstrong** [comment]
@MaxWattage If you still are having issues please create a new issues.
