### ISSUE TITLE
Unable to locate build directory for package: <package_name>

### ISSUE THREAD

**Issue by MrYelameli** [ros-industrial/ros_qtc_plugin#198]
Hi.. I am new to ROS. I am using ubuntu 14.04 and ROS indigo version. I have installed qt5.9 version.

 and then followed this link [http://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html](url)  

and [http://ros-industrial.github.io/ros_qtc_plugin/_source/Setup-Qt-Creator-for-ROS.html](url)

And then followed this video [https://www.youtube.com/watch?v=GqBzI7O9h8A](url)

I am getting the following error. 
**"Unable to locate build directory for package: trail2_pkg"**  

Would you kindly tell me what is the solution.

**Comment by Levi-Armstrong** [comment]
What type of error; is it a segfault, error printed out in the compiler window, etc? Also if you can provide a screen shot Qt Creator with the error this may help.

**Comment by MrYelameli** [comment]
Hi.. Thanks for your reply. I am trying again by removing everything and installing again. I just uninstalled ROS. How to remove qtcreator ros completely which I installed by referring [http://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html](url). 

I will install again ROS and then qtcreator plug in, I hope it works then. Waiting for your reply. Thank you.

**Comment by MrYelameli** [comment]
I couldn't understand so I uninstalled ROS and qt and installed it again. So now my problem is [http://ros-industrial.github.io/ros_qtc_plugin/_source/Setup-Qt-Creator-for-ROS.html](url) in this link under **Setup Clang Formatting** at step number 8 when type "Clang", there is no New Tool to pull up. I have already followed the step 1 to 5 and installed Clang formatting. I send you screen short Tools--> Environment--> Keyboard. 
![env](https://user-images.githubusercontent.com/11991052/32640705-551c8a92-c60d-11e7-8354-66a24719e12b.png) 

Waiting for your reply. Thank you.

**Comment by Levi-Armstrong** [comment]
The wiki is missing a step when setting up a new tool. You need to name the tool, the default is `New Tool` and you should rename it something like `Clang-Formatting`. Then when searching Clang it will show up. Also I have been using the plug-in Beautifier which provides more option for using clang formatting. You will need to enable the plugin under Help>About Plugins and load it by selecting the checkbox.

Now for the error are you refereing the `Warning at the top of the page`? If so that is normal until you add the file to the CMakeLists file and build the project. Until it is added to the CMakeLists and built it is not added to the code model.

**Comment by Levi-Armstrong** [comment]
@MrYelameli were you able to get everything working?

**Comment by Levi-Armstrong** [comment]
No response
