### ISSUE TITLE
Can we use "WebEngine" and "Data Visualization" in this Qt version?

### ISSUE THREAD

**Issue by EdXian** [ros-industrial/ros_qtc_plugin#199]
Hi , @Levi-Armstrong 
Can we add `WebEngine` and `Data Visualization` module into our ROS project?
That is to say,I want to install Qt community version and add `qt57creator-ros-plugin` to it.
Any idea?
Thanks

**Comment by Levi-Armstrong** [comment]
If you follow the install procedure it will install the necessary qt libraries for Qt 59. They get installed into /opt/qt59 directory for which you will need to use qt tools `qtchooser` to add it as a version if you want to develop with it and easily switch between different version.  Also I am not sure if the libraries you mentioned are automatically installed when installing Qt Creator but they are available shown below.

Also just because Qt Creator is built with a specific version of Qt does not mean you have to use the version of the libraries it was built with. I would recommend using the native version available for the version of Ubuntu you are working with unless need to use this version because it is newer and the native is missing capability.

Now if you insist on using the qt libraries downloaded from Qt Libraries you will need to build the plugin from source. @oxoocoffee has created an nice script for making it easy to built from source which is in the root of the repository `setup.sh`.

`sudo apt install qt59webengine qt59datavis3d-no-lgpl`

**Comment by EdXian** [comment]
Hi @Levi-Armstrong ,
First , thanks for your advice.
I had successfully used webengine in the previous qt57creator-ros-plugin (see [here](https://github.com/EdXian/ROS_QT_GUI/blob/master/googlemap/CMakeLists.txt)).  however , I got error as follwing after update to this version:
```
CMake Error at ROS_QT_GUI/googlemap/CMakeLists.txt:13 (find_package):
  By not providing "FindQt5WebEngine.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5WebEngine", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5WebEngine" with
  any of the following names:

    Qt5WebEngineConfig.cmake
    qt5webengine-config.cmake

  Add the installation prefix of "Qt5WebEngine" to CMAKE_PREFIX_PATH or set
  "Qt5WebEngine_DIR" to a directory containing one of the above files.  If
  "Qt5WebEngine" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/edxian/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/edxian/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:290: recipe for target 'cmake_check_build_system' failed 
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failedBut
```
It seems that cmake can find module like `Widgets`   `Network` ... but cant find the `Webengine` because the wrong `CMAKE_PREFIX_PATH`.
I have no idea how to solve it.
Thanks!

**Comment by Levi-Armstrong** [comment]
OK, So I had to make a change because by default when loading Qt Creator 57 it would load environment variable that would pointing to /opt/qt57 and this caused issues when building rviz plugin because ros is build with a different version. So I remove this so it does not automatically set up your environment to point to a particular version of Qt libraries. Try launching Qt from the terminal using the command below which will setup the environment pointing to /opt/qt59 and then rebuild your project. 

`/opt/qt59/bin/qtcreator-wrapper`

**Comment by EdXian** [comment]
@Levi-Armstrong 
It works fine for me again!! Now I can use both datavisualiztion and webengine in my ROS project.
Thank you very much.

**Comment by Levi-Armstrong** [comment]
Glade to hear!
