### ISSUE TITLE
Missing Import ROS Workspace in Qt 4.4

### ISSUE THREAD

**Issue by HadiMohamadi** [ros-industrial/ros_qtc_plugin#203]
Hi
I've installed Qt Creator 4.4.1 (qt 5.9.2) in Ubuntu 14.04 LTS. Then followed [this](https://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html) Installation guid.
Everything installed correctly with no error, But still there is no " Import ROS Workspace " option in Qt. I can not find " ROS Project Manager " in installed plugins either.

**Comment by Levi-Armstrong** [comment]
Did you install Qt Creator from Qt website?

**Comment by Levi-Armstrong** [comment]
Actually looking at the version I am almost certain you have. I maintain my own version at the moment until we can get an installer created for this. To lainch my version of Qt Creator try '/opt/qt59/bin/qtcreator' then lock it to the taskbar.

**Comment by HadiMohamadi** [comment]
I installed it using Qt Creator online installer. Actually when i lunch Qt with desktop icon, There is no `Import ROS Workspace` or `ROS Workspace` option, But When i use `qtcreator-ros` command, `ROS Workspace` is placed under `other project`.

**Comment by oxoocoffee** [comment]
I have same use case. For that reason I am updating project to have enable qt installer creation package. It should be available soon. Watch for PR. We will update Wiki with necessary steps when ready.

**Comment by Levi-Armstrong** [comment]
@HadiMohamadi The reason is the current plugin is not compatible with the version install using Qt Creator Online Installer. When following the install instructions you added two ppa's one to my version of all of the Qt Libraries and the other to the plug-in. When installing the plugin it installs a version of Qt Creator in /opt/qt59 directory and creates the qtcreator-ros. If you had not installed from online it would of created a desktop icon but sense one already existed it does not overwrite. There is not an issue having multiple version of Qt installed.

As @oxoocoffee  mentioned to get around having to maintain a custom version of Qt Creator he is working on a installer to enable the ability to install it in the same directory as where the user installed Qt Creator using the online installer. This should help streamline the process and make it less confusing for user.

**Comment by MaZhengg** [comment]
Hi, here is a problem. so we can NOT compile the .pro project in your version Qt creator? Cause  when i open and compile the project with some file(earlier created in the .pro project and compile successed)  in your version of Qt Creator, some of the head files cannot find. If this situation is right, is there any way to meet an emergency, such as include some head files manually? thanks

**Comment by Levi-Armstrong** [comment]
Can you provide an example so I may recreate the issue on my end?

**Comment by MaZhengg** [comment]
Well, it was a mistake myself, sorry.  Now I should ask in another way. If i want to compile the ros workspace using some head files of Qt, what should be done to the CMakeList.txt file to include the QtCore QtNetwork as the dependencies? thanks

**Comment by Levi-Armstrong** [comment]
Resolved
