### ISSUE TITLE
Outline View on Top Sidebar

### ISSUE THREAD

**Issue by nathangeorge1** [ros-industrial/ros_qtc_plugin#214]
Hey @Levi-Armstrong,

Is there a way to move the outline view from the sidebar to the top bar? Currently, it says "# manipulation|manipulation" in the section where it used to show the outline view (I don't know what it's used for currently either, just cycling through and old names)

![image](https://user-images.githubusercontent.com/2744891/34060073-235c8cbe-e1b0-11e7-9e52-b5cf4ec0cd49.png)

Thanks,
Nathan

**Comment by Levi-Armstrong** [comment]
The "Outline View" moving to the top bar, I believe it is still there. On my screen it is to the right of the  "# manipulation|manipulation" and says **<Select Symbol>** but if you drop it down it shows the Outline View. Ah, I just tested mine and it is because your screen is two small to show it ans in my case two. If you remove the second editor window or shrink down the sidebar it will show back up.

So the "# manipulation|manipulation" is for syntax highlighting, basically there will be one for each node/library that uses this file. Mainly because if the file has section of code enabled or disabled based on a defined parameter the syntax highlighting could be different between different nodes/libraries. In my experience I have never had to change it because they are all the same, but it is possible.

**Comment by nathangeorge1** [comment]
Is there a way to remove this syntax highlighting dropdown from the top bar so that I can still use split view? I removed the outline from the side, but only when i remove the split will the outline view appear on the top bar.

**Comment by Levi-Armstrong** [comment]
I am not sure, I would look under setting for the text editor.

**Comment by nathangeorge1** [comment]
I checked there but I didn't find anything about editing the toolbar. Googling also didn't show anything. I'll assume there isn't a way to remove the syntax highlighting option from the toolbar.

**Comment by Levi-Armstrong** [comment]
You could make a request to the Qt Creator development team.

**Comment by nathangeorge1** [comment]
good idea; i'll try that
