### ISSUE TITLE
Hide .git folder in the project view

### ISSUE THREAD

**Issue by beetleskin** [ros-industrial/ros_qtc_plugin#216]
With plain Qt, I'd hide the .git folder within the individual packages. This seems not to be possible anymore with this plugin.

**Comment by Levi-Armstrong** [comment]
So plain Qt manages the tree differently than ros because we have a lot of files that are not always in the CMakeLists file so I treat it as a folder tree. Current the Project Tree supports filters which I plan to add additional filters for this purpose but have not had a chance to get to it. I will tag this as an enhancement so it does not get missed.

**Comment by Levi-Armstrong** [comment]
This has been added by PR #234.

**Comment by Levi-Armstrong** [comment]
@beetleskin I have just released the latest version. Please see wiki for new install procedure.
