### ISSUE TITLE
Attach to Unstarted Application

### ISSUE THREAD

**Issue by ghost** [ros-industrial/ros_qtc_plugin#288]
I thought I'd open a separate issue from #286. I want to debug with the following technique:

1. [Setup Ubuntu to allow debugging/ptrace](https://ros-industrial.github.io/ros_qtc_plugin/_source/Setup-Qt-Creator-for-ROS.html#setup-ubuntu-to-allow-debugging-ptrace)
2. [Attach to a unstarted process](https://ros-industrial.github.io/ros_qtc_plugin/_source/Debugging-Catkin-Workspace.html)
3. Setup Run Configuration
![image](https://user-images.githubusercontent.com/2744891/43200552-e6979854-8fe3-11e8-95b9-a3cf28a86508.png)
4. added a 5 sec wait after the NodeHandle

But where I think it's supposed to stop at the breakpoint, it throws:
`poll failed with error Interrupted system call`

**Comment by nathangeorge1** [comment]
any update?

**Comment by Levi-Armstrong** [comment]
I currently receive the same messages but does not seem to affect the debugger from attaching in my case. Does the debugger fail to attach?

**Comment by Levi-Armstrong** [comment]
Have you tried removing the `ROS Step: debug movement GeneralTester` and running through the process?

The reason I ask is there is an open bug report on this run step which may be causing an issue. Also if you are already launching the *Attach to an unstarted process* manually, this run step is not need because it basically does the same thing and could be conflicting.
