### ISSUE TITLE
How to use this plugin to debug ros package code?  

### ISSUE THREAD

**Issue by HeYijia** [ros-industrial/ros_qtc_plugin#29]
Hi, dear Authors:

 I installed this plugin with Qt5.7  and learned how to use it from [this issue](https://github.com/ros-industrial/ros_qtc_plugin/issues/25) and wiki.

But, when I want to debug some ros package code using " Menu Bar > Debug > Start Debugging > Attach to Running Application..." .  I found some pkg  labeled with [develop] can be debuged.  While other pkg labeled with [master] can not be set breakpoint.
![image](https://cloud.githubusercontent.com/assets/11751752/17218064/150299ee-5519-11e6-9310-e70d40fdf271.png)

Could you tell be how to deal with it?  Thanks in advance!

**Comment by Levi-Armstrong** [comment]
Hello @HeYijia, The text between the brackets signify the current branch of the package, so this should not be affecting the ability set breakpoints. Are you able to set them and they are just be ignored? If this is the case, this is usually because the package was not compiled in debug mode.  If you did compile in debug mode I would perform a clean then rebuild in debug and see if that solves the issue. Others times I have had where packages had flags set in there cmakelists.txt file that would force the package to always be build in release no matter the mode set through catkin_make. Hope this helps.

**Comment by HeYijia** [comment]
@Levi-Armstrong  Thanks your tips. I checked original cmakelist.txt file of the ros package and found the author set CMAKE_BUILD_TYPE Release flags. After delete it and rebuild in debug,  the breakpoint not be ignored.

**Comment by Levi-Armstrong** [comment]
Great! Is it ok to close the issue?

**Comment by Levi-Armstrong** [comment]
@HeYijia, Also when using this method for debugging you may need to put a sleep in your code sometime depending on how quick it executes to allow the debugger to attach.

**Comment by HeYijia** [comment]
Yes,  I should have notice it. Since I can contorl the input, the debug from running application is not a problem. Debug from unstarted application is better choice. Thanks @Levi-Armstrong .
