### ISSUE TITLE
Nvidia jetson support

### ISSUE THREAD

**Issue by robotlinker** [ros-industrial/ros_qtc_plugin#316]
Hi.
I am doing some development works on the Nvidia Jetson Xavier, any plan to support the ARM architecture ? Thank you!

**Comment by Levi-Armstrong** [comment]
I can easily test it do you know if there is a ros docker for ARM architecture?

**Comment by robotlinker** [comment]
Thanks, can you give me a link for the docker image? I will give a try...

**Comment by Levi-Armstrong** [comment]
Sorry, I was asking if you knew of one? I see if I can find one if not I will build one.

**Comment by robotlinker** [comment]
HI Levi, any progress or plan on this part?  thank you!

**Comment by christian-rauch** [comment]
The build process was greatly simplified since this issue. The official documentation and the new CI build script rely on the officially distributed Qt Creator binaries to further simplify this. Those only support 32bit and 64 bit Intel/AMD architectures.

For other architectures, you will still need to obtain Qt Creator development libraries from your distribution or compile from source. After this, you can follow the instructions again and set the `CMAKE_PREFIX_PATH` accordingly.

I am happy to review a PR that adds arm64 docker support to the CI pipeline.
