### ISSUE TITLE
Can it compiled on Xavier?

### ISSUE THREAD

**Issue by liuchenxv** [ros-industrial/ros_qtc_plugin#396]
Hi Levi:
 I want to use the plugin for ROS  on Xavier which has arm64 architecture and ubuntu 18.04.
However, I can't setup the plugin with the ways on Wiki. It seems to be for devices with x86 architecture& ubuntu 18?
 So ,can I have any other ways to compile it?

**Comment by Levi-Armstrong** [comment]
I have not tried building this on arm64 in a while, but I have successfully built it on arm64 as debian using this [rules file](https://github.com/ros-industrial/ros_qtc_plugin/blob/debian/xenial/debian/rules). It may provided some insight into what compiler options you need to set for it to build.

**Comment by christian-rauch** [comment]
The build process was greatly simplified since this issue. The official documentation and the new CI build script rely on the officially distributed Qt Creator binaries to further simplify this. Those only support 32bit and 64 bit Intel/AMD architectures.

For other architectures, you will still need to obtain Qt Creator development libraries from your distribution or compile from source. After this, you can follow the instructions again and set the `CMAKE_PREFIX_PATH` accordingly.
