### ISSUE TITLE
Could not start process "catkin" build --cmake-args -G 'CodeBlocks - Unix Makefiles' -DCMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by Mateus224** [ros-industrial/ros_qtc_plugin#410]
Hi I just started to work with ROS. But i m getting some problems with QtCreator.

1) [ROS Warning] Unable to locate package myPackage build file: /home/mateus/seaclear/tut_catkin_ws/build/myPackage/test3.cbp.

2) If I create manually a package it doesnt show up in QtCrator 

3) if I build the project I get this Error: 

18:34:02: Could not start process "catkin" build --cmake-args -G 'CodeBlocks - Unix Makefiles' -DCMAKE_BUILD_TYPE=Release
Error while building/deploying project test (kit: Desktop)
The kit Desktop has configuration issues which might be the root cause for this problem.
When executing step "CatkinTools Step"

I cant find similar problems in the web... I tried to use catkinMake and catkinTools. I hope somebody can help me.

**Comment by Levi-Armstrong** [comment]
Do you have catkin tools installed? I think it is `sudo apt install python_catkin_tools`?

> [ROS Warning] Unable to locate package myPackage build file: /home/mateus/seaclear/tut_catkin_ws/build/myPackage/test3.cbp.

This may not be an issue, since the project has not successfully built. After the first successful build it should go away.

> If I create manually a package it doesnt show up in QtCreator

This is a known bug, but if you reopen the project it should then shown. The current tool that is used to monitor the workspace is currently not monitoring the top level src directory for some reason.

**Comment by Mateus224** [comment]
Hej thx, yes that was the error. I missed catkin_tools.
