### ISSUE TITLE
Building ros_qtc_plugin for Debian Buster or other linux distros

### ISSUE THREAD

**Issue by lepalom** [ros-industrial/ros_qtc_plugin#413]
I would like to build ros_qtc_plugin for Debian buster but I'm a bit lost and I have not found any documentation. I'm sorry if there are some wonderful README and I have not seen it.

Checking the code and the scripts I have understood that:

- Obtain the sources (git clone)
- Checkout the branch with the same version of qtcreator you want to use for.
- Obtain the qtcreator sources. Put them in a directory ../qt-creator.
- Build ros_qtc_plugin, but although I put the qtcreator sources I got several link errors. So, I don't know if I have to put the build directory, or the sources. Or both ..

And I'm lost here, in this step.

Please, could you put some kind of recipe to build this plugin in some distro agnostic way. Because, believe me, there's live outside ubuntu ...

**Comment by christian-rauch** [comment]
The steps for building the plugin are actually quite simple. You first follow the Qt Creator build instructions from https://wiki.qt.io/Building_Qt_Creator_from_Git and then run `qmake` form the plugin source directory.

Assume a development directory `$DEV` (e.g. `export DEV=HOME/dev`).

Build Qt Creator first:
1. `cd $DEV`
2. `git clone https://code.qt.io/qt-creator/qt-creator.git` (I omitted `--recursive` because it is not required to build the plugin)
3. `mkdir qt-creator-build`
4. `cd qt-creator-build`
5. `qmake ../qt-creator/qtcreator.pro`
6. `make -j`

If you want to build the newest Qt Creator, you need Qt 5.14 or higher. You can obtain this easily using the binary Qt installer from https://www.qt.io/download-qt-installer. The default installation path is `$HOME/Qt`.
To build Qt Creator with a newer Qt version, you have to use `qmake` from this version, so the `qmake` step would be `$HOME/Qt/5.15.2/gcc_64/bin/qmake ../qt-creator/qtcreator.pro` instead.

After Qt Creator has been built successfully, build the plugin itself:
1. `cd $DEV`
2. `git clone https://github.com/ros-industrial/ros_qtc_plugin.git`
3. `cd ros_qtc_plugin`
4. `qmake`
5. `make -j`

This will build the plugin and install it to `$DEV/qt-creator-build/lib/qtcreator/plugins/`.

**Comment by christian-rauch** [comment]
The build steps have changed significantly with the newest release. Building the plugin does not require building Qt Creator from source anymore if your architecture is supported by the official binaries.

See the new build instructions in the `README.md` and create a new issue if you encounter build problems. I am going to close this issue as it refers to the old unsupported build scripts.
