### ISSUE TITLE
Should the default branch be updated 4.14?

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_qtc_plugin#421]
@christian-rauch Should we change the default branch to 4.14?

**Comment by christian-rauch** [comment]
Once https://github.com/ros-industrial/ros_qtc_plugin/pull/417 is merged (feel free to merge if you are happy with the issues discussed in https://github.com/ros-industrial/ros_qtc_plugin/pull/417#issuecomment-763601334) I would always have the default branch track the current state.

This could be done in two ways:
1. the default branch is changed every time a new release happens (4.14, 4.15, ...),
2. there could be a `devel` branch (since `master` is already taken for the documentation) that keeps track of the current state and branch out every time the API changes (i.e. with every Qt Creator minor release).

Maybe the `devel` branch option is easier since it does not involve changing the repo settings with every new Qt Creator release. I think the ROS behaviour is similar, in that the branches stay the same until the API breaks.

**Comment by Levi-Armstrong** [comment]
A `devel` branch sounds good.

**Comment by christian-rauch** [comment]
I went ahead and created the `devel` branch after the 4.14 merge. Can you @Levi-Armstrong set it as the default?

**Comment by Levi-Armstrong** [comment]
Done.
