### ISSUE TITLE
How do qt read system environment from ~/.bashrc?

### ISSUE THREAD

**Issue by SSmarshal** [ros-industrial/ros_qtc_plugin#428]
I come up with a strange problem, when I run catkin_make in terminal, everything was just right, but when I used qt to build my project, the problem raised:
![image](https://user-images.githubusercontent.com/46676996/106600509-7d33a080-6595-11eb-9df9-8d101aba8908.png)
I looked up to Cmakelists: 
![image](https://user-images.githubusercontent.com/46676996/106600759-cc79d100-6595-11eb-812e-f0fac14f2a15.png)
And in ~/.bashrc:
![image](https://user-images.githubusercontent.com/46676996/106600850-eadfcc80-6595-11eb-8b02-0139fcb28bfb.png)
And I tried to set the environment, but nothing just happened:
![image](https://user-images.githubusercontent.com/46676996/106600961-0ea31280-6596-11eb-8b4c-9399197bb183.png)
I am confused. Thanks in advance!

**Comment by christian-rauch** [comment]
Rule Nr. 1: Paste the raw text instead of screenshots of text :-) This makes it searchable for others and you can copy&paste it easier. Use the triple quotes (\`\`\`)  at the start and end to format the text with monospace.

Can you try with catkin_tools (i.e. `catkin build`) on the CLI? CatkinTools is now the default in the plugin, so make sure that you use the same build tool in the GUI and the CLI.

**Comment by Levi-Armstrong** [comment]
So I have ran into this before. It turns out that application do not use the bashrc file so you have to add any custom environment variables to the Qt Environment under the projects tab. Now there is a similar file to the bashrc for applications which you could add these to but then every application would have these in their environment which may not be desirable.

I do see that you have tried adding this to the Qt Project environment but not sure why this did not work.

**Comment by christian-rauch** [comment]
The environment variables that are set in build or run configurations change when you switch the configurations. So you have to make sure that they are set for any build/run configuration you use.

Alternatively, there is a way to set environment variables in the project configuration:
![qtc_env_var](https://user-images.githubusercontent.com/8226248/106638625-fde5a300-657b-11eb-9e50-142f54725168.png)

I think those defined here are global, i.e. apply to all build/run configurations.
