### ISSUE TITLE
Why can't my QT project send roscore instructions to the terminal

### ISSUE THREAD

**Issue by lianbashou123** [ros-industrial/ros_qtc_plugin#441]
![20210914_112134](https://user-images.githubusercontent.com/88788972/133189697-c6a3810f-1415-4964-98e3-0cf49da9ed16.jpg)
Why can't my QT project send roscore instructions to the terminal

**Comment by christian-rauch** [comment]
I cannot read what is written on your terminal. Can you translate into English what the error is?

Can you be specific about what your try to do, what the expected outcome is and what is actually happening?

The code snipped you show is trying to open `gnome-terminal`. This is not ROS-specific.

**Comment by Levi-Armstrong** [comment]
As @christian-rauch mentioned I believe this is not related to the plugin but I will see if we can help. It looks like you are making a system call to launch a roscore but it is not found which is most likely due to the environment of the terminal not being setup such that it can find ros. I see the commented out system call which tries sourcing ros and your workspace but assume that did not work. You may try && between commands to see if that solves the issues `gnome-terminal -x bash -c 'source /opt/ros/indigo/setup.bash && source your_workspace/devel/setup.bash && roslaunch path_to_launch_file'`.

**Comment by lianbashou123** [comment]
Yes, you can open the command box of ROS and execute it by adding the source environment and instructions after Gnome terminal. Thank you very much ~ I found that it has been solved today

**Comment by christian-rauch** [comment]
@lianbashou123 Can you in future:
1. paste the raw text (with syntax highlighting if possible) instead of pictures of your screen, and
2. close issues that are considered solved?
