### ISSUE TITLE
Why do I add the image transport ROS library to. Pro, but there is no related class member function definition in the display library? Didn't LIBS succeed?

### ISSUE THREAD

**Issue by lianbashou123** [ros-industrial/ros_qtc_plugin#445]
![723bba2e452b724f](https://user-images.githubusercontent.com/88788972/134165408-98577d74-a946-47ea-bfeb-c69d3bb8e722.jpg)
Why do I add the image transport ROS library to. Pro, but there is no related class member function definition in the display library? Didn't LIBS succeed?

**Comment by christian-rauch** [comment]
This is yet another generic ROS/C++ question. This is the last time I am going to answer your generic ROS questions. Please ask such questions at https://answers.ros.org and use the raw test instead of screenshots. In future, I will just close these kinds of issues without an answer.

If you read your error messages carefully, you will notice that it says `undefined reference to class_loader::`. This should tell you that the [`class_loader`](http://wiki.ros.org/class_loader) is not installed. You should be able to install all dependencies using [rosdep](http://wiki.ros.org/ROS/Tutorials/rosdep). In any case, the package you are looking for can be installed via `sudo apt install ros-${ROS_DISTRO}-class-loader`.
