### ISSUE TITLE
Build Step - CatkinTools Step GUI is empty?

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_qtc_plugin#448]
@christian-rauch I installed the latest plugin and the CatkinTools Step GUI is empty. Do you experience this on yours?

![image](https://user-images.githubusercontent.com/9803128/134452003-47c8ffe5-a1fb-45c3-b41d-c3fa01af8fbd.png)

**Comment by Levi-Armstrong** [comment]
Not sure if it was an option I selected during the Qt Creator Install Plugin process but it put several plugins in `QtCreator/lib/qtcreator/plugins/lib/qtcreator/plugins` but the ones distributed with Qt Creator are installed in `QtCreator/lib/qtcreator/plugins`. Due to the install location, the plugins are unable to find several libraries. Also, the Share directory was in the incorrect location. I moved everything to the same location as the other plugins content and now everything works except the build and clean steps GUI. It finds the styles and templates now.

**Comment by christian-rauch** [comment]
Yes, I found that if I install the plugin archive via the Qt Creator GUI, it will extract the archive to `~/Qt/Tools/QtCreator/lib/qtcreator/plugins`. Since the archive contains a file hierarchy, with the library and shared files, this creates a nested `Qt/Tools/QtCreator/lib/qtcreator/plugins` and hence places the shared files in the wrong locations.
I think this is a Qt Creator bug, which expects the plugin archive to only contain the shared object, no folders or other files. But this way plugins could not install shared files.

The issue you described, is it from the most recent `develop` branch? It's the same issue reported as #444 and the plugin archive from this PR solves the issue for me.

**Comment by Levi-Armstrong** [comment]
Should we create a new tag with the latest?

**Comment by Levi-Armstrong** [comment]
I pulled the archive from the CI for the latest commit and it solves the issue.

**Comment by christian-rauch** [comment]
Yes, let's create a new `0.4.1` release. @Levi-Armstrong Can you update the version information in the CMakeLIsts.txt and push the tag?

Edit: Nevermind, I just did this myself. The release will be available at https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/0.4.1.
