### ISSUE TITLE
CI Release process is failing

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_qtc_plugin#458]
@christian-rauch Do you understand why [this](https://github.com/ros-industrial/ros_qtc_plugin/runs/4217022690?check_suite_focus=true) is failing?

**Comment by christian-rauch** [comment]
Yes, I think I know what is going on and I was about to open an issue for this.

The last release https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/0.4.2 is missing the plugin archive from the CI because there are conflicting release tags for the `actions/create-release@v1` action (https://github.com/ros-industrial/ros_qtc_plugin/runs/4217022690?check_suite_focus=true):
```
##[group]Run actions/create-release@v1
with:
  tag_name: refs/tags/0.4.2
  release_name: refs/tags/0.4.2
  draft: false
  prerelease: false
env:
  GITHUB_TOKEN: ***
##[endgroup]
##[error]Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
```

The CI is set up such that a release is created automatically when a new tag is pushed. I assume that a release was created manually via the web interface and hence the CI script refused to upload to an already existing release (`"code":"already_exists"`). The release description from this automatic release will be initially empty but it can be added/changed afterwards via the web interface. Alternatively, the release text can be added to the CI script (see https://github.com/actions/create-release#example-workflow---create-a-release), which could also be read from a text file via a bash script.

I couldn't find a way to make the `actions/create-release@v1` action append to an existing release. There is [`actions/upload-release-asset@v1`](https://github.com/actions/upload-release-asset) that can upload to an existing release but it is (also) not maintained anymore.

In the short-term @Levi-Armstrong can you create a new release by pushing a `0.4.3` tag? This should create a new release automatically with the plugin archive attached. You can then copy the 0.4.2 release text over via the web interface. In the long term, we should switch to a newer and maintained release action that also allows uploading to an existing release.

**Comment by Levi-Armstrong** [comment]
Thanks for the explanation which makes sense. I just pushed a new tag.
