### ISSUE TITLE
Plugin cannot be loaded

### ISSUE THREAD

**Issue by masterhui** [ros-industrial/ros_qtc_plugin#47]
After following the install procedure, I get the following error when opening qt57creator:

![2016-09-02 10-43-30_qtcreator_ros_plugin_error](https://cloud.githubusercontent.com/assets/3931642/18198006/98fbcb6a-70fa-11e6-9361-532118ff88ae.png)

**Comment by Baliano** [comment]
Hi,
I have the same problem. I think qt57creator package has the plugin version 4.1.0 and not 4.0.2. I do not know how to fix this dependency.

![screenshot from 2016-09-02 11-20-28](https://cloud.githubusercontent.com/assets/21882335/18199126/51e3dc2c-70ff-11e6-9592-efec0afa28e8.png)

**Comment by gavanderhoorn** [comment]
`qt57creator` recently started building against Qt 4.1.0, not 4.0.2 anymore. `qt57creator-plugin-ros` would need to be rebuild to match again.

@Levi-Armstrong: it would perhaps be an idea to not use `>=` to specify the `Build-Depends` ([here](https://github.com/Levi-Armstrong/ros_qtc_plugin/blob/8137b184c395fc32f6f092bfae6698207338d521/debian/control#L7) and in other places), but to use a strict equality to prevent these kind of things in the future?

That way when the PPA(s) update, installation will fail early, instead of appearing to succeed and then to fail when actually starting Qt Creator.

**Comment by sun11** [comment]
The same problem with me, then i manually download 4.0.2 from https://launchpad.net/~beineri/+archive/ubuntu/opt-qt57-trusty/+build/10040216, and use dpkg to install it, it could fix this problem temporally, and just wait for the update.

**Comment by gavanderhoorn** [comment]
@sun11: nice work-around. That is certainly a temporary way to get things to work until `qt57creator-plugin-ros` is rebuild.

**Comment by Levi-Armstrong** [comment]
Yea, It looks like qt57creator has been upgraded to 4.1.0. I will work on upgrading the plugin to 4.1.0 over the weekend.

**Comment by Levi-Armstrong** [comment]
Hello Everyone, I just release the new Debian for qtcreator version 4.1.0. You should be able to perform an update and upgrade to get the latest.

**Comment by masterhui** [comment]
Awesome, I will check it out on Monday. Have a good weekend!





On Sat, Sep 3, 2016 at 7:00 AM +0200, "Levi Armstrong" <notifications@github.com> wrote:












Hello Everyone, I just release the new Debian for qtcreator version 4.1.0. You should be able to perform an update and upgrade to get the latest.

**Comment by masterhui** [comment]
qt57creator opens without error now.
