### ISSUE TITLE
Debugger does not stop at Breakpoints

### ISSUE THREAD

**Issue by gre1234** [ros-industrial/ros_qtc_plugin#60]
Hello everyone,

unfortunately, since today, the ROS Qt Creator Plug-in does not stop at Breakpoints.

On the terminal, where I started sudo /opt/qt57/bin/qtcreator, it shows the following:

QIODevice::read (QFile, "/proc/9692/stat"): device not open
QIODevice::read (QFile, "/proc/9173/stat"): device not open
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"
loadAllColorSchemes
QIODevice::read (QFile, "/proc/9701/stat"): device not open
QIODevice::read (QFile, "/proc/9702/stat"): device not open
QIODevice::read (QFile, "/proc/9708/stat"): device not open

QIODevice::read (QFile, "/proc/9692/stat"): device not open
QIODevice::read (QFile, "/proc/9173/stat"): device not open
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"
loadAllColorSchemes
QIODevice::read (QFile, "/proc/9701/stat"): device not open
QIODevice::read (QFile, "/proc/9702/stat"): device not open
QIODevice::read (QFile, "/proc/9708/stat"): device not open
QIODevice::read (QFile, "/proc/9711/stat"): device not open
QIODevice::read (QFile, "/proc/9714/stat"): device not open
QIODevice::read (QFile, "/proc/9715/stat"): device not open
QIODevice::read (QFile, "/proc/16212/stat"): device not open
QIODevice::read (QFile, "/proc/16216/stat"): device not open
"The command \"/qmake\" could not be started."
**\* UNEXPECTED STATE TRANSITION:  Debugger::Internal::GdbAttachEngine(0x6bef230, name = "GdbEngine") "State changed from EngineRunRequested(7) to EngineShutdownRequested(19) [master]"
QProcess: Destroyed while process ("/bin/bash") is still running.
QProcess: Destroyed while process ("/bin/bash") is still running.

I didn't write all lines, there are several more lines similar to this " ... device not open"

It's so weird because it worked till today!?
I always clicked on Debug-> Start Debugging->Attach to unstarted application--> and then choose the executable and start watching and then I click Ctrl+R .
Does anyone know why?
Thank you so much!

Gre

**Comment by Levi-Armstrong** [comment]
I just updated my system to see if maybe an update was causing the issue but I was able to attach and debug a ros project. I think the issue is running qtcreator as sudo. Have you tried running running it as user? You will not get errors and warning about particular config files not having permissions if you ran it as sudo which you can delete. 

As for the device not open, I am getting the same output but everything works fine so I suspect this is not an issue.

**Comment by Levi-Armstrong** [comment]
@gre1234, were you able to solve the issue?

**Comment by jackros1022** [comment]
hi,how do you solved the issue? Can you give me some hints

**Comment by jackros1022** [comment]
I get this error:
No executable specified.
Debugging has finished

**Comment by Levi-Armstrong** [comment]
@jackros1022, I will see if I can help, can you outline your process you took for debugging?

The preferred process:
- Compile in debug mode. Note: Make sure the build configuration is set to debug.
- Debug-> Start Debugging->Attach to unstarted application--> and then choose the executable and start watching
- Then press Ctrl+R (Assuming the run configuration is setup to launch your node, otherwise you run it from any terminal on the machine and it will still attach.)
- You should see the debugger start to attach, usually when this does not occur it is do to the process not being compiled with debug.

To verify that the executable you are interested in debugging was compiled in debug, execute the `file path_to_executable` and make sure it has `not stripped` in the output.

If everything above is what you did and you find it was compiled with debug, then I have another process that may work.

**Comment by jackros1022** [comment]
@Levi-Armstrong  Thanks very much!
According to your process, I have solved the issue. I think the key point is about how to debug with dynamic link library,but I do not know nothing about dynamic link library.I greatly appreciate your help.

**Comment by Levi-Armstrong** [comment]
@jackros1022 Great to hear.

**Comment by facontidavide** [comment]
This should be documented in my opinion.
My suggestion is: 

if the user is trying to debug a __roslaunch__ or a __rosrun__ configuration and the "debug" button is presses, launch a pop-up message that reminds that the correct process require the manual use of "Attach to unstarted application".

I don't know how complicated that would be to implement

**Comment by Levi-Armstrong** [comment]
Created new issue #83 to add @facontidavide requested feature.
